-- =====================================================================
-- Prion v2.0 — Migración 004: poblaciones y supermercados (OpenStreetMap)
-- Datos: export de overpass-turbo del 02/10/2026 (Baix Empordà),
-- procesado con tools/osm/ (ver README). Geometrías en TWKB base64.
--
-- Decisiones de Angel: la población se deduce de la casa (02/10); los
-- supermercados son reales, empiezan inactivos y se descartan los que no
-- tienen espacio público adecuado al lado; la zona de saqueo está en la
-- calle peatonal o plaza junto al local, nunca en parques o jardines.
--
-- Criterios técnicos (Claude):
--   * Límites municipales simplificados a 15 m: solo sirven para saber en
--     qué población está una casa o un supermercado.
--   * Zona de saqueo = (calles peatonales, plazas y áreas viarias a <= 40 m
--     del local) - (parques, jardines, parques infantiles) - (el propio
--     local); se queda la parte mayor; mínimo 80 m². Las calles peatonales
--     que OSM tiene solo como línea se ensanchan 3 m a cada lado.
--   * Locales duplicados en OSM (nodo + edificio del mismo nombre a < 40 m)
--     se fusionan.
--   * Resultado: 115 supermercados en OSM, 26 con zona de saqueo válida.
-- =====================================================================

CREATE TABLE public.municipalities (
  id          serial PRIMARY KEY,
  osm_id      text UNIQUE NOT NULL,
  name        text NOT NULL,
  area        geography(MultiPolygon, 4326) NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX municipalities_area_gix ON public.municipalities USING gist (area);
ALTER TABLE public.municipalities ENABLE ROW LEVEL SECURITY;
-- Nombres y límites son datos públicos; el cliente puede leerlos.
CREATE POLICY municipalities_select ON public.municipalities FOR SELECT TO authenticated USING (true);

ALTER TABLE public.players ADD COLUMN municipality_id integer REFERENCES public.municipalities(id);
ALTER TABLE public.pois    ADD COLUMN municipality_id integer REFERENCES public.municipalities(id);
CREATE INDEX players_municipality_idx ON public.players (municipality_id) WHERE age_band IS NOT NULL;
CREATE INDEX pois_municipality_idx ON public.pois (municipality_id);


INSERT INTO public.municipalities (osm_id, name, area) VALUES
  ('relation/348057', 'Albons', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAUayySWy5IEE7AkQjgicAg+kAcYBNKoB5gLqCa4G9APABEq+AbIBQs4KxAGBApIMhQEwIaIDOwaoAYIDuAGEAUaoAWt40wOeAfMLtgH1AsoKdfIBtQJzV2GtAwtdjwGOAYUBbbUExwI4PXtpFeEDOgmZAsECP5cDPhld7wdnY5cDrwIJAt4C7wYFoQMzuwrDAsMCmwGPAfMB1QqdAdMD4wEfvQKoAqEEMvsBzAL7AuQBkQX4BM0EmAKZAaoGMYgBhgGEAgEMV/oCBiD2AdwDJ8gCZw7hAooEkQJa+wG8A2eLAakDpwHdAYIF6wE=', 'base64')), 4326)::geography),
  ('relation/343837', 'Begur', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAbICxqAnnuf/A7IEIjUslQEENCgtHHAEDTA0DDtQjQEklQExYRRACjMWwAEerwIXdxAEHixOkAEGhwEkdkJJFl4iESRsBA8qOBiAAgbcAr4BWHYpGt8CgwFuXANOViQCQt8BDoYDnAEmcGImYyDfAVdcwAGnARypAYEBDZMB3wEzf04cWikyQDhRICg0oQEcgwEbGZgBggEoGDY7FFIqhAEFWW5gVBpJvgEACkxzHAo0iAERB1s6YRvEAVRgsQFAxgEOCmoSG0CIATYLAGbJASICeGqoAYYBByUcSDrgAlicAYABlgJGpgFccAJBKUwDwgGuAaABBTQmJTZAGUc0cmA0jAHMAQh/XsIBpAHyAiOaA8ABkAK6AYEBngHjAUTBAZoBmgHSATNkgQO2ARZMRBQTLCoLiAGoARcmWAa8AYQBLRAMbnBwDypeRFJbYgAkKBHKAmBkowGgAU4+PS63Aa0CDccBcQvZAZ4BaxtNiAG6AUI2tAFfDhlw2QE7EoIBJxe1ATwNSMkBOCFSFDyMATPeAQNyMBZ+TlgaGQE6RB8ISJQCAw5MUZYB3QFYB6QBmgEmMG6BASdcRLcBJiQqLVilAQZHX5kBVpkCIr0B3gFlFAI0UxwaKjsuPAUAJl1wOWMzIgkfkwEM4QHMASCEAZUBLPMBQzEuUTuxBUVDQOUCLzdEOQkTPG9TKmWTATcFJa0CXFlMLAwtaERGTVhgEj0YKnqWATgKNH0adiJdDhc8Qip3Gn2mATQyBxR1IGlorwLaA7sCoQEZHlsrPC8/NWsQWydtiwJ9QG+dAocBGosBKYkJzwrrFdkMoAuXBb4GwRDKBIUFmw23A7kBlQGrAQixAbwBrQEz3wJagwIn7QKBAfsDBsEBFeMBX/sBCr0FkwOxCccBzQzhA0LRAjeBAVJvGOECkgF7M48CtAWNA5gDuAHYAgZEJZ4BpQWeAt0CL9sBpgUSWHoFVF5C1AEPNp8B/BSUAoYBO94B2wIJV5gBFcAEgAEEeLAB4gHqAz92FDCAAroTtAE2rQFOHWxwsgEi9AEp5AFGPlDUAg7eAWewARpiPBVA', 'base64')), 4326)::geography),
  ('relation/343834', 'Bellcaire d''Empordà', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAUTmnSbY8oEEnQGiB/cB0AQvzgL1A4ABrRWhB4EUgwODBacG6QmtBqkB5QLFATMQowGNCJsC6wkPMesBjwKJApUBQ+8DN6EDoQPUA78CD98DXgdQ3wL6Agk2xwKIBVXsARA+ajD1AY8BqQLsAQY49wGVAYsBkwSzApoB/wGQAUfKAzuOATucA6UDzAXhApID6wP4AQHcAVOkAVz4AQTsCe4C1gGSAYkDMIEBsgQy5gNboAI9sAQGzgF+tgPgAqoE4ASmArQCVvgFJJoLcSTIAZwME4oJJqoC/gKRAagFLpIDeJYCkwHEAweMBw==', 'base64')), 4326)::geography),
  ('relation/344130', 'Calonge i Sant Antoni', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAbEBwIMliOz+A7gFyAOWBtMFvAS9Ab4DgAHUAdYBvg//BB31A7YDFaQF1gKOBIsCrAbVCOwJ1QEC0QOICOULSNEBIhcFaqIBjgGAAQYoOIoBJE4XAS2QAQYrTE0DADBkKgQzMFo/IDRWsgFCLogBOCsaYjkuLmCwA7ADmgFGlAEGFlI2KS4gGi0iVlo9ggE8TEcFPDo7bhMsMBAxSf4BUxZeECE+IhUoBjs2hAEgKVxYETY4QRZgJAk6OQo4PkNKFkgqDx4WiwFWHliECYIIzAKYAXgtOykiD4ICqgECJGc5S05SsgGAAipmV10tKguiAoQBfRkpIg1YaHSYATSSAQlqWVFPugJghwEHFygQXHpsyANoTIEBK4oBSijqAzAyESSLAROqAUwypAIgzgMbGpgGV1ylAcIDqwE+zwEZ0wHEAoECENUDkgKxAZwBhQEsOXCoAfICStYEX54DHpwCeeIDvQH2Aq0DxgKhB0L/BMwGGq4KnwG8Bc0C9gKzBaoCb4AEhQrgBKsN1AO/DOcD4xVMngOBAzKRAlI1FmWSAWkVX2JJSrsBCbcCmAHlAa4BLR97mgFxFNUByAHdAe4BPRYvACmzAWsbtQG/AX02JX2nATAVGWGpCPUEoQ+lCL8BQbcaqwSTCYEBigXnFugMiQk=', 'base64')), 4326)::geography),
  ('relation/347518', 'Castell d''Aro, Platja d''Aro i s''Agaró', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAboBsKMl4pH+A3pXd/sBUjoNT04ZA58BWmFQBT0VFCVSATpEOwSoASwKUEwmQQk6TksVCjKNAQWiAVgnGmJCH0J6DHqMATgOIjc+AaIBVEFS1QELIR7qAUQabpIBRi6CATMOggFQDTR5DowBLI4BdAcuRhAEejcKKhRBAwkkaHKBAQIdfEKSAVhAbgcOKFUIAyp+ZJIBBwlBLDCIAQhQTkUZTDYfOMABDigyMxEZNGRkhgEELDdKJJcBygGPAkIbsgE4hALuBYIPsAOGBuQCnAPgAYoBN0SEAZQBogFmPikoJjIVDkxDAEIQGzSUATk8ZhIvNC4tMmAFKRZQAjIyTg0HU5QBBR0siAFAJ0JQLNIBH2aKAWnqAYcI5gsB0gPrCdYBqwbWCI0EjAKjBdUCtQMWHvYDvQ+ABdMB1QG9A3+7BL4BlQbUBbcFxwMoaVUNA13LAqUBE8MBzwH/A2CbAtEBnwEGwQKLA+EEAe8B4wY2pQNOgQGNAZECqQHrBMEBwQIrX29eYYgCMwy7Ak6fARmXAnyPAaABhQOyAd0BGckBKllT7QFwkQFQxwJLmwEvxwPyBe0GYaMDFJsBlgH5AeoBN5QBXbABCKIBgwHSAvUI5gKXA7YBVOYBYeoHrgOQBL8EvgFuyAIRrgKXAeoDkwP4AdkDjgGeAYIBjgSkAogB/APpA+YB7QU=', 'base64')), 4326)::geography),
  ('relation/343218', 'Colomers', ST_SetSRID(ST_GeomFromTWKB(decode('pgABASj4oCTY1IEEiAHfBfACjQS+BxGCAcYCTsIDR/4BrwK2A0OGBKYBpALKAbQB3AE3ugXLAowCOaQChwFOiwGEB9kGqgXlAtoHlwWiBLgFtgO0BmjKCJ0C3gfzAZIEWz/NBYoB3wa9AukGG+sEYLMEG/sDoAGxBpwEwQHhB5YDDbECzQKfBUPPApkF8AH1BbcBiwKrAWc=', 'base64')), 4326)::geography),
  ('relation/343216', 'Corçà', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAWLaniW65YAE+gGwAYsKzgbHAT6zAQ3JBWivAZYBlwZBCp0C9QmLA88GvQKVAaMDuQECoQOFAccDMZ0DuwElqwKtAQUP2wGXAR0DZbMCAMEBTv8CHStn8wEqrQEVywPQAy66A5kEQjXKB6UDnAEi0gGfAYoBzwIfJ8wBvQERnwPCAT2GAXMFabQBwwFVZXVl0wWpAokCzgE97wHvA8sBFA7/AW4EL9MD+wexAoQB7QHZBLUBeL0B5QFhjwH7A0cd+gqLDdACoAKiCgLMAcMBA2HMA8sCGk2YBByWBPkErAOHA27ZAXZNpASzARU3lALNBVglggGvBMUBowGsAuMBjgNGmgMRiAVBAmOIAwQsK8QEjAHSBFJXpAPyBNoCdpoB3AK0BPACjgewCaAG/Ab8Bf8G1gh5lALWBewFqAO0BbgEwgL2AZoC', 'base64')), 4326)::geography),
  ('relation/341395', 'Cruïlles, Monells i Sant Sadurní de l''Heura', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAbQB6qIl3L7/A8sf+AZ2hAajAgapAsYBeIACFtYCiQOgArUGlgJ57AO7BJIEWcQBCeQBmAHyAhDKAcwBqgHgAqIBOkgdxgKkA9gCwgLwAo4B9gENugHDBYAITcwEwwG2BDBM3gJ4vAGSARzAAWKoASrIAqYBcENOsQEMe8wC/AL8BVaCA9ABwAFArgEGwAGBAYQBhwG0Bb8BhAMd9ALRBFHDBIsBKyyHAwMBZIcFQpkDEo0DRasC5AHGAaQBgQGwBFcmkwLOBRY4owS0AXVObdoBqwOIA5UE+gSXBBsZTssDzAIEYosBqgGdASTDCQvhAaUBvwO5BJEChQLtB8cD7QSHASv7Bo8LkQTbBAmxBVeJBtMB/QaOAeEGkQLvBuMK4gS3BqkDswvaAc8C5AKLCIkGb3zJA0rZB0qPAdMDSaUKsgGFAwmXC+ED7wEQyQFM8wEv/QGRAY8DAIkB0QEomwFr/wEYT68E8wLvBX1ZqwFTHW0m6QGSAijCBfkVrQNDnwOKAqsCgALHA5QDiQcLtQX/CMkF5QX/AqkBnwGDBIUC5wLPAp0CTS5n7AGlAQdl4AFJ9gH3AcACtwF+0QHsA+MDvgEltAaOAZIKZLAvkweIBOMFwgONCr4S+wHsBjOlAbcCii4a0AyXB5oUiQmmDZkE5AeBA44C0QGUCYIBuBqsBMABQqIPpgiqCPYEGmIvFn6oATUmwAF+HLYBtAFsACoVMO0BPpcBqAFDjAKZAXIgfK0BLneqARX0Akm8AWFKFmCRAWoVZlE2ApYBfdwB0wKiAqMBugQcMA==', 'base64')), 4326)::geography),
  ('relation/347773', 'Foixà', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAVWq+STytIEE4QhxhwcLkwN9ywIt6QRGwwI7+QEgpwW3AoMDGekBME9sFvgBoASCCH70AvAB9AIK9gFVlAGZBvYDzQFKzQj4BakF5gKDB9oGTYwBowKIAYsCOrkFzALbAThHGacCvQNEhQSwArUDSP0BjQLhCD73BVXnAc8C0QKvBeUGdgPEAocBIqcBjgGdAZ4BiwOEA4MFN/0BStEBmQHDAcIErROjAmmKA2uAAbcGsgapAaoE+QFN5QHIA1nmAoEEZocDvgSmBvABigG0DngXgQGYB1aUBGJKIfoERhZ/7gEYTCu3AWGYAzusAS5wV54COcoBYsoEHq0DlgqIA6wFf64C2gFcKbICgg7mD7gP2AO1EOQG8QaGAc8EGg==', 'base64')), 4326)::geography),
  ('relation/343540', 'Fontanilles', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAVLM4SW6l4EE8QdjzwIIkwJUjwhkwQWGASfDAaoFmQM7QWrDAdAC3wJYLZQETckDtQUD+QGeAa0BTZUE8QQUL7MDpwIXEGHGAReoAocB0gHhAROjAewBRyP1A9QBU8gC+wGUAc8BALcB0AKJA9ABnQOqAQ8QgQGaAY0CkAWjAtYBC/ID+gHqASeNAsECWpECUcMDqwHZAcACmQKqASisAZYBrg/iAcoGnAT8DrkByg7tAfgL4QLSCVOcBVC2D44DvAnGAvMB9APLBJkBswnLA78C5QGZCvIE6QgPgwbSA78F4AK/AvQB3wGWArsJtgTxBfgEkQsu6QSrAZsM+QEb2AGHA48F9QTgA8MFwgEmnAKGAa4BCZQBMkKDAYgJ6QPeEnrsAQ==', 'base64')), 4326)::geography),
  ('relation/341396', 'Forallac', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAV7IhybU9v8D8QRCX+ADCKYCswG4ApMCxBVBTjHQA/EFtgK7BjuADZgNL5AC/wfSBtUB+AGTAZQCB/ACnwFyGeoCvgKeBvcF+gGTAZQEswXeA6EFuQSbAwclVJcBBwkk8wMC6wRpyQE48wHMAaMEEPMBQOUEiwGlAfcEowdOMYkDzwIHyQJbI/UE8QJt2wG7DrMGd5UJU48EX88EpQGfAoMBtQHVAT3bAfMCG2SjBOoChwlJW/oB4QGgBckCSdkBFIMChwLfBjDBAeoBuwP/AY0EpgGxA+oB1wGWA+MBhAGBAfQCqAF4K267AeIE3QGcApUDG48BkgGdDMUJ9wTGBMsMiQLJCfMFswqkAbkE5BVLwAzoA6wN0wOGCt8EcP8DtAWpAs4C9QLkAogBkgZQ/g7mDv4X1wiDBb4HXdYD0AOkEb8K/gyHA5IOduwL', 'base64')), 4326)::geography),
  ('relation/343538', 'Garrigoles', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAUL+lCWwhoIEpwO6B+UHzgd7IesBngOlCMYEwwZmrwJerwPYAa8BU+MBcPMCtwF2NeICwwWvA/UGWcsE5QPVB40DDrUCrAHNB7MBywOHAVDDCDxbV/0CvgLDA5UCwQEfnwJp1QGhAU8fZasBXXXvAr4G8wGKB6ACzgIQ4AHnAawB7wL8BOUCwAJfugGVAZoBeKYEXJYDpAGQAQmsAYcBwAZzAUSWAWb4AjI6rAEJ5AHXAS4hkAFQugXEAdYDAogC4AGgAZQCugIIggHKAigInAPaA7gE6QHMBbABCZACa5ADfg==', 'base64')), 4326)::geography),
  ('relation/340341', 'Gualta', ST_SetSRID(ST_GeomFromTWKB(decode('pgABASvetSb84YAEL6oB8wH4ApcCzgGTBY4PIhjPAt4IkQqaBNsC4AGbBPwBlwSqBRK6AbcJgAWjAoYB7QOSATFucxGZCawC5QQ2vwpToQRnsQUpeesB6gPdEoQBhwkxQQqTAYUBrQElmwLEBcEB9gTfA4gDkAUc1wGcDPoB6gSsAZILLfIF9wS8CbUE4AGVAsAC8wHABd8ChAbRA+oIEA==', 'base64')), 4326)::geography),
  ('relation/340345', 'Jafre', ST_SetSRID(ST_GeomFromTWKB(decode('pgABASP80STu6YEE9AGRBJ4C3QdnyQi1A7MGoQS3BdwInwVWkwEGlwGdB8cOBrUCngJdhAMaqAW4AvoBH8QCPOoERcwCLpQDfogHDOIIchD2A4YBBOUClg+RBpIPgQK8CrkBlgG/AmD7BOYCqwHwAt8B6AHNAg+JB58CvQb0AbEBWQ==', 'base64')), 4326)::geography),
  ('relation/345519', 'Mont-ras', ST_SetSRID(ST_GeomFromTWKB(decode('pgADAQTq5ybUif8DjwEaGT+qASYBBklIHUI4Ci8wW48BchQBSDXSC+8EtASFDcYK8wET+wH2BdcFxgcfzASnB64CwgOIBMMByge5ARIy1AJrogO7AQAflAJnOBBUiQOWAZECMEi0ArMD6gRblALvA1DnAxD1AzWlBrsCgQetA5MDK7EItwPPA6MRXtUDhAW9B+gENLoDzQLiA8UEvgupBQOnCL0ByQKgB5kC9AFxhgM78AHhAeIKnwWaEIMFpgSaAZIM8QIGRjsnEkgjE2lENEZtmAE+coABJEyYAaMBaipyNgISTBQtRAglbG5QgAEdOR4SNi4NM6IBSRlfPEwi', 'base64')), 4326)::geography),
  ('relation/345513', 'Palafrugell', ST_SetSRID(ST_GeomFromTWKB(decode('pgANAQTw8ia8gv8DBAMGBAkAAQRQEgMJCAwDAQEENiMEBQQEBwIBBMoB2QICCAcBBgUBBKsB0AIQAwAEDwABBLABkwERCg4LBAIBBBPFARYAGwoGCQEFuwHqAjYMBTQ/GxAjAQRtKCMXLhAJCAEErAGtASYQLwQKEwEEB4gBIgAFKBsnAQU/TTQGLBxjBAQlAZgD8h7IR8oBLA46pgE0DRzaAhvyARRKLJcBbjg8RTRgJpMBGzM84QFMCzKZAQh+ICRsqQFCAkRPAzdGjQEMmAEuDjgxFFwLNowBbBcRPEogHUJnC1AmC2LzAZwBSA9pMAc+QwIBYpABbJYBIiZLVDJqMykzWD+UAgtQHlcmOBZQEwom3AEsDi9mABwedSSAAQkUIFA1Fy4kI0QoNlx2JTomEi9uSBlINCSNAQFeJAk8Ng6TARJILHNKRhhDBkQ+tQF+Mi7mARcGIGkciAFMXENgCBcyRQ0TCqgCapcBBHkxMGCKAUZZCkYynQEITDIxGOkBAi8mwgEwcxi+AW5NIooCRide2AF4gQE6jQECByiIAQk9QDEn1QMDFj8/K9EBKd0BaNMCDT1P4wFF8wEqsQEha29NHjWuAbkTswEv/wF1E+kDQK8B4QEDd78Ef5cBFgpY3QHcAoUBPPsUkwI1oAHTARBdQQZTV3mlBREw3AGdAt4CjQGQBTEy+QIElwO3AbMFjgM0kAKRAXwX4gJRcDiCAS2WAhM8nwKsAUKKARWkAqEBuAEkRin4AYMBuALPBhzVBkvPASaFA5kBvQEZqQP7AnsdF9kB9wEIvQFrvwIXDYEB6QIuLVP3AQbZA+UC/wEv9QKrAacCUNkBBusBcNsEQnXrC4gDkQ7ACv0Msgi4A5QDLIIHrgOmBrwC9gM26AMP8ANPXJMCtAPpBEezApICL4oDlQEPU2g3IJMCvAEAbKEDMdMCugERxAHJB8EDhwSoB60CIMsE2AXFB/wB9QX0ARSUEoUPLlwBNywKSogBEDFyJqIBO2J8ITY1G0M4Nx+9ApoBIYQBWC5dDAZAYRITSCY8eCg3ECYqmAENKxY6IEcETDQEIDkRGB5KAiw+UC2sAZoBigEdUk4UN2pibSwQSD8PHTozGyg2MQgISnocACIzCUAkAT4pDQQdEQObAc4BXiBPTkYOGVJaRxoWM2Q7FwyAAUooFzAoDz50gAEWDB8dXjgjDE6AAS5UCxA/DkBKDDAZE3VSmgGAAS8pJV4BBiUyhgH0AUaqARVGmQHAAUggIUIOKwweRnIOF25eNBFshAEBNEZUK5ABaDmoAUkWN3p01gHcAVq+AiiSARk/SVQKXGtjTcUBiAEtIfQBkQGgAXLeAeUBNgERUpABR5ABCFBJdBWqAQwoOIIBEA9EVGIfFR8uMjIpIGgyA3xEOkcgRBwZNFBWF+gBYhcSIjPsAYIBBQPCAR45QgEnogF4Fn9MSlopWogBNpIBhwEOQiQzFmq+ARs8MDFGXDIHUE49eIQBjQEDXHprPmQMH0R6Ph9wmAEfQcABhQJuH0poHhA2aQIQOm9iYQ2XAZIBAjg=', 'base64')), 4326)::geography),
  ('relation/345522', 'Palamós', ST_SetSRID(ST_GeomFromTWKB(decode('pgAHAYUC2IYmnvP+A1hbGZcG1AV3RikRUW6oAf4CZYQFqwJyjQGDBm9pPFQ/RosCNAhX0gE6CAkkygEcVtcCLgZjjgK0ARoWV94BIFAhOKsC1QEJEkP5ASMZcHkRDjOLB38oOaMBFLABR+wL5AE9fcQBfXiIAbQBMTJWYh0eJmwGelo3UsIBigL0A74BPS67A5sBwQHIApwEzAEaK9ACbk7NAcEBP84BCBdrQyNAEWuDAdsBbS4x1AFyngHOARDQAWvUAY4BOk9SQlZEI84BCF5i9AEiDCeUASlmQDxBGi5eCgQw5AIeSmwlgAF0ChJIK3RREiiQASFOKSJdFawBUjcQIDxLCBAsZzClAQfrAYoCtAHSAqQBaDgDCzU0CAB6eESsARoyQXAdGD0YIAYnKBguKVgQHExqJQ5A1AEAWIYBPDUfQG5EB3J1QAleFjQ8GQdgjgEFUxzCAWpcSS4uXAVmYWI2IDMeogGkATjKAgWaAmE/wQJ4gQFmEWA2Dk5xPB1KjAETHjZyY7wBIWIqjAGwAeYBEJABSBpFmAF+Ek0NhAKOAYABcAkUTSwQLjUKNNwBExs0MgYANnJx4AFhDsYBSgAQdV4QCDJYHwAyKBuKAUoPUGoFBUwlEx6aAUAIEz0yJhAfCXKWATqkATEmHDMumgFeRgQqPUgwOicoQJkBNiRqogFklAE/QHSRDPICpQSZATkQ3w/0BOEKoAXvAeIB+wJCtQTlAsMBmAHtAgGJBXjhBO0F0QTBAfMBowGbAdUBSXZ9jAWVBJgD7wGkAk0KS0fvAWKDAbIBhwPvAZ0EsAPrAr4BwwOiBoUG+gGJDuwFswQM4wKHAaABuwUZrQqABcsGogdBrgPFAr4B9QJ64QMdmwJgnQNJ1QSnAfECOm+GASuyAZsB1gORAoICD9QBwwLQARqsAT2mAcEDAQTQa9oOEAIDCgsLAQQuCQ4FAggPAQEEJy4YAwkODQkBBO8BGCIaJQsEDQEEmAIzCSILGxYFAQXLASKSAQ8UGqkBJgQv', 'base64')), 4326)::geography),
  ('relation/340869', 'Palau-sator', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAS3C/SW2mYAE4gNaRcQDpgF4jAGEAvYDavgFmwHwCk66CG5WcsYCNjRcpgZCnQKwAwDQDZMB9guDBKAKBbQBY+wBCqgExAiUB/cL4gLJDu4B+w66AckGmwStD+EBqwGVAakBJ0SVAXHzAlvJCLQF3QOUAZME+AX5Ab0CnQYa6QKgAXEI7wKUAZMC1gH3AdQHhwZc2QL/DJcNvAY88gW1Ag==', 'base64')), 4326)::geography),
  ('relation/340871', 'Pals', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAUHEtya+ioAExgWGA5YS+gb0D8wF4gveBOwV2gyKCdAKjAEqiAEZcJ4Cfj9ujAJcKGwPQDY7MFwsGh28AqIBmQP8A9MChAaJAWaHAc4DQzTVAtAHQzRD6ALNAYIEhQG0BrEB9AIPkgH9B88B0wPYAb8DDM0BogGjAoQBiQd4wQO4AdUP0wnPAwK7CcUCsxG3A50DJdEJVMMIkwcJpwRk6wEGswGEBJ8KlAH1CxKlDowC2QKcAYkEiAPHAuQCXrQBlwPkAcECFpkB7gGlA5QBjwGMAbsFuQIlQ4kBWJkBiAE9', 'base64')), 4326)::geography),
  ('relation/340870', 'Parlavà', ST_SetSRID(ST_GeomFromTWKB(decode('pgABATzaniW65YAEVDOcARbeAVacBNICmAZAzAGMApQBC3qaBJIBCjiAB8AB1gFs5gFC1AR7POkFUrcCxwHrBG6dBI4CRIoB6QFCF6QBwwQNNsgB8wIQQpwDsQESI2SRASr7A9cBsQF92wWZAQtPwwEpxRI5qwU3yQFhnQI6vgGPAo8BPSDnAd0B7wVojwEV6wFnGVqdAtADCQL9BCglXUu6CdcEjgvGAwmeApgGQrABlQHKBWe0AQ7IAT2MCs0G+QGvAQ==', 'base64')), 4326)::geography),
  ('relation/340541', 'Regencós', ST_SetSRID(ST_GeomFromTWKB(decode('pgABASCetyb6gYAE0AYbhAG3Air3ASNFogG3ARajAkGJAaACqwHODOIDsgnIAb4FlAP8AQnkAWDCARb8AwXuAoIBhAIo4AJZrgE0sgG7AawBB7oBlgGcDbgDyQSGBb0GwhCfC5gF4QvdBPMPywWVEvkGxQWFAyXDCA==', 'base64')), 4326)::geography),
  ('relation/344927', 'Rupià', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAT2SxyTM84AEaPEBoAPBAb4BEijLAdACIKABiQEh0QGmA5sBNskHmgRBLbkDzAPPA64BFvQBKSxogAMewgFNtAIABGaYAR4Q3AGuAQYmrAKeA7wByAMyogOGAboBAZYBpAO4BYQCuQnYBF5MJyYB/gTPAwpZngJoGhbsAWeQAd4B8AUf6AGQAT6tAugCqwEtlwM8uAFiSyztARcVgAH5BEVJIpMEYZcHVRiCAbMOd+8BiQG9BKUG9ALfApYB6wEmvQRDbw==', 'base64')), 4326)::geography),
  ('relation/340210', 'Sant Feliu de Guíxols', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAeUBisgk8ub9A2QdpAEoTDV+ATIeSSwQUq4BUSFCdywqVl0aCz5YTtYCOJABYlwAiAFPGzeQASmwASgtMskBAgWQATEULnZGJsoCEGesAd4BFA1MaAi4AYoB0AHuAZgDugGQAji4AWruAheSBOQBzAI1hgSeAa4EPuwBZwIjhgEMQjGuAaIBkgESDiVAFCY1Yg8DQSIaBitCAhMzWDExwwFCMYYDay4gOzwIZNgCO2TIASMdHXCZAQ8bZmpKzQEBE8gCtwF2iAEuSwECUEAqTRZwQIMBCE5GTQcPKUFSLpYBkAESqwEqJHLQAo4B9AEcMjkCSFYaxgIfnAHdAUIgNxI0HAdEKwBEGgFYMgMKiwI2BAvUAeoBCQ3DAWihAY8BT/MGvwEaLfIGzAHwAY4BHi0xGYABByMshAEWMlxuZZoDeFIbGyGIARIaE08NagIgIj8iXChhIKQBLncLE2TCAWIWVF8gMiaZAWZQGJwCKaIBQCJKFgYJSeQCCDs80wEM0gI8WTbZAggaZFMEZjhTDygeZRKuAR4aOE0BhAFORQISJq8BD5oBJgwuTQA2XOUBFxkcrAE0XwcoIjcazQEDaFIVMm4SKxBQJhcuQT8LQjosM27UAaIBggT0AbIEZuACMeUB7gX7A+oDowKHAYEBjQSNAZ0B9wHaA+kDlAOtApgBxwISvQFtjwTABOkHrQPlAWK1AVPlApgDkQejAtkM5QGNNIsJpgPBA6cB1QLnB+EEzQOfByrfAq4KswiAA7cK8wHDBH2dBU4HLlKOAkj6Am1ycKoCQNAHSIwBcgVk2AF2', 'base64')), 4326)::geography),
  ('relation/342520', 'Santa Cristina d''Aro', ST_SetSRID(ST_GeomFromTWKB(decode('pgACAQXcsSSG3/0DEUdWCEkYBigB3AG7CasFlAFyIBk8QisiPFI9Vh40wALYAdIBRIoBO0YgOhcLKkQMYh0VNDIiNwkdaBgLMgRNIGx4UALYAZcBIgprNARMmAFfWioCNCkAIDhzKn6eBfQBxAT/ArgKrQq0CCngAs4DoAfoB+IEqAHWAqUDwgOONIwJ2gzmAZIHpALRAvYIoQGEAa8BB5MBXukBOJUB+gETnAFipAPxBe4GMMgDTJwBT8gCb5IBVO4BKVoaygGxAd4BnwGGA3uQARqYAk2gAQu8AocCNF1iYHDCAizsBMIBkgKqAYIBjgGmA03kBjUC8AGMA+IEBcIC0gGgAV+cAtABgAQUxAHMAqYBBF5WDidq5wyKCYkF6BaNAtIB4weCA6UNmgSZFIoJzwyYB4kuGbMBzwK7ATtdQo0BdSnDAUUpCLsBPT8mbZsBKoECeTerAXJ5A5UBjwEjiwHpAXdVuQJRUecBywG7AYcBAlUtK19KS23VAV6PAQTnAe8EkQIHqQGMAoMC3Ai5AuoQ1Q7uA5EEQQGQAe8G8gGhAkYtggIdtAKpAgHpAmSNAmGLARJ50gGFAhx1zAFDF2lgtwE9swFavwEn7wFyqwEE7wGgAZMDEUOxAYkClwNJ4QFz8wEc1QS6AbEFC70CQcUDMMMFCOkBKZsCJssCrwG1A0DlArgBjQq4AesFE1FlG78BaS2bBC1AxwHsAf8CZ5MCxgGBASDJAX5ZpAKDAx2LA44CowLAAYEBCo8CiQLHAjO7AdwOsR+sEtcExgXvEa8OgQqUA8UBqgJPRj+mAa0DpgTtAwdna1kGb44CgwGaAQIImQGKAQRwLcQBhQJ3swEoReoDL07vAYoBGUQ8fgHSAX8ecZgCywG0AWCABFmIAVK2BUgZaCQDV0A=', 'base64')), 4326)::geography),
  ('relation/346730', 'Serra de Daró', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAUCkxyWcmYEEqw7oAd8GogPxBKgDkwJ02QW4AdUFvAK1BIgDBtEC8QGbByiZDlyZAeUB5wV9Q5IBKSRjsgERQZsD9AIPNccBxAQOGKMB6gFBQ4kBngSNAuwEbbgCyAHqBVF8O0HTBGvlAb8B1QE3/wb0AaUCwgXbAYQC8wQ0D5gEA4gCVoIBnAFe8ALcA1jsAsgCjAL2AmCkA7wC2gXfAZoCpwKIAcUBGA9iqAIYMLQD8gQTTpYEnQGuAQT6AcoDtgWTBE5XLs8C4AJpxAE8QqkFmgMoxAE=', 'base64')), 4326)::geography),
  ('relation/346724', 'Torrent', ST_SetSRID(ST_GeomFromTWKB(decode('pgABATaetyb6gYAEJsQIhwE+V5oBRIoBugImiwG8BZMBkAHtAaYDFZoB4wHCArMBmAPjAl2HA8gCmwGKBKUGQTNbxQI1VXG5CG3vCk33BZwB9QNpiwGDAqUBd0bDA+EDWTLPA0JNlALDFbQBtwIHpQJg3wPOCYMB7AFv2gEFqAJP9gKsAYACMNoD5gL4AQUuVOoCLQ6CAcACGL4BbPgBBxjaAXwesgP+ArYBGMwDpAGKAS/WBkw=', 'base64')), 4326)::geography),
  ('relation/346722', 'Torroella de Montgrí', ST_SetSRID(ST_GeomFromTWKB(decode('pgAJAQWEsCeim4EEARsiFwwMKygBBMkBoAwBBwQIAQABBN4DhQ5LB0YLBhQBBQ+EAYwBEQNIQxhDTQEFpAJjUEphMlMxZkkBBYUKpBArKAcFDEMoIgEY+gThDTxQYB9clAGaAQ8qWDkaCDxtD11tLRgzKU9AAz0tFiMlaygYJIUBDjohBH8pCqoC3QEZWAEmmQPMAxJAqAEVFypIBDpoTQIKLEoqECUkElTEAZYCATFEfQoFigFMVtkBGFFAE2rhAbEBEVOBAhIbSDUfK0CTAiGHAUs/lwFCoQGwAUUfIa4BazZ5xgEnrAF3UiRHSAHAAqd27T2aCvEEwALmAbQJzAPMBJoB9AHzA9ADAdYP1AnCA7cBigd3pAKDAc4BoQHAAwvUA9cB/gfQAeMB3AUQjALXAbAJDKQEhwH2Aw2SBVLSBfgC+A4EkALuAbQI2gHqA/QD2gOUAUKEA5kC9AG4AVgIACx7AbUBowHDBcoDzAJ8vAG/AUoeiQGEAQJIjAJWdH/QAViaAYUBtQT3AXAruAS2AnQnjgFjCZcB/QK1Ap0BANQBFegCrgI4ugHsAkCsApYBoQEUOegBvAGmAQDiATIbSlR3vAE6FyEu5gEqVIIBcyLDATOQAV5HPJ4BSDxsdgcsLwpCNAbRARQzKu0BcW8cCTlhYocCQgVqQixRQhJI6gFokQEkQRsAOFc8HIIBR0pqFgdCKTU7CBY2KxkRHmZWKRBuKDSUAYQBAx5eeIsBZgUS7AKPAWi7ASfHAWBtL0MaWTgn/AFPAg8stQFjaJQBEpoBrwEVUGDlAhyRATYqSoUBggHTAVnQAawBggECASrHAYYBpwElV3KdAU5xJ1dYDlRZCwOKAUlImwENT3QYcC9aTKgBrgKUAfIBEkJSC2ROb3QIT7gBkQF6VwF/ayGNAVMhf4gBGYABQTdBQDwwD3hfHBkppwEpFUo3BrMCXXRkD0BSDBhiPx6XATVxJAlSxgHEAZ0BlgLFAdQBYxIeaH0Oa04SXlIyFpgBdRkpT1ELM2RChAFTiAFTCBWEAW2KAV4kN3hjenUKBzCLAR17KiRONA0fZiwWLCUkZqcBnAIvVxFssQF0kwEHL2B/GXsiNfYBQi4VmAHVAZwBggEIL+wBeQYKUisOLzu5AQohenY+TYIBexdHbw/hAWsWoQEpGD0pAzwx2QGCAf0BNucBUQdbvQEmL2vDAVBxDZUBXIUBF/8BqAJdEoEBjgF51AFWzgF2fE0c2Qxu0QTNArEGqQSxB70B2wOxAfcK0QLZB90C+wSZAQiLB5QBwwN3lQItkQOSAacFqQL9AokJJZsMFCPHAZkLctcGNbMG6QLfAqkEfbUDOP0FXJ8CMeUDggGxBOYBBXIzqgKEAY4C9wG8BiLkC5UF+gXDBPIJowRKa2MPHr8BahAiMaMC2wEJkwSjA4EB9wTNAtEBrwSVBvMHMm3uA5EBpAKFAbgJ/wQRuQGYBKkFnAT7AdwC3wGSCpkE0ALdCCEXlAWND5gCzQH0AfcCMKkB', 'base64')), 4326)::geography),
  ('relation/343313', 'Ullastret', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAU625yWMzIAEXMoIcvQCwQGqAsEBhgGsAdoBUsQDWZICjgLCAukBKPED+QHVAQyPBaQCmQGOAg+CAakBEM8BngPPAooDALgBkwHQAccC/AHTAVQk9gPrAUiZAu0EX6MDiwL1AusCxwLbA1dd7wKBAZsBhwJVywQUgwL0BMEF3AHzAaYCkQEJeZkEkwEMywGLApcGP5sE0QLdAVWbARVTNPUBmQK3BMECpwOzBdUF6wV6kwKAB9UIlgE+ggODAtICGYABlwKKAT2qB21u5QHMCnZO8wHiA9cBmANq0AIIMooDpAdNpgH4BOYEjAH0AT+kBA/0AcsBygE37ARq9AMBCiOYAQgmU5wDCKIFugQ=', 'base64')), 4326)::geography),
  ('relation/343314', 'Ullà', ST_SetSRID(ST_GeomFromTWKB(decode('pgABASna2SXWloEEpA2OAaIEaMAKVOYENZoJqwJ0EpYG9AfSAbAE+ATOAqQDggEKlASkAtwBITJpDx3AAWQQSWzxCaQE+QXEBOMLlgW7BiGNAvgBzQOLAusJ7QKrAa0C+QLHA7cGkQJ5tQJCcU+bAaMCZa0DAU0dFN0BkwJGK4UB5gGBDNwCxQbYAlXQAgc=', 'base64')), 4326)::geography),
  ('relation/343307', 'Ultramort', ST_SetSRID(ST_GeomFromTWKB(decode('pgABARbkkyWYiIEE+gScAuYB6AVbmgEnmg6MAtYIH5gBlwOSAvECngG3D9cDgQ7lDyqxAtkBW4ABrQKHA6sFrgOVCoYDLqIQJsQBKgxQ3AWaAbIBfg==', 'base64')), 4326)::geography),
  ('relation/343305', 'Vall-llobrega', ST_SetSRID(ST_GeomFromTWKB(decode('pgABASOwoibArP8D4QPGBLkDzgLnBDP9F9gI/Q7lDoMGT6YEC4oO6wWGBvkBxAOhBuwCvQGeBK8DiAPwAYQBsQHwAWFMSE4J8AGjApYElwN+iwVKdZwB1gH0AaQB0gTCAeIE7gWKBXfuAgLEAZcBrATgAvMBcp8HmgK+AcoCBKgIvQuqBQ==', 'base64')), 4326)::geography),
  ('relation/347894', 'Verges', ST_SetSRID(ST_GeomFromTWKB(decode('pgABATKUmCXQq4EEzgeZBdYFuwLaBbcBIHLzBOYFhAXoAbIB8gGMCMYE2gK2B8gC3gHeAu4G8QGgA48NowHlB+AH1wJ1kQLJAk8b5QIxNSSxAgrDAaoFJbYDQcoB3QGsAl013QEioQF8ZxVjMPkDzgPfAswH3QX0A/cCMZUBZQJDvwZ0qwGIAY8BCpUDowHXBG9nY4ICuwqSBpEP5gKVD4UBAw/1A9AEGfIGhQGoE4EI', 'base64')), 4326)::geography),
  ('relation/347609', 'Vilopriu', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAU7IyCTkqoIE7AKrA3DXAuMBIv0C9QvpE+sFkQvhBpEVrwG3AVU7jwLhBYwB3QIZnQPXCg6RCJsBiQMTmQP+CKgBdN8CLcEBeL0D9g/nC1rLAgafA6YBpwOsAWi4AYwC7wH2BdACmgWgBUSyAs4ClQMOwgHiB7IGmwT8A58BtAQc7ARf6gYc4Aa+As4FiQGOApoBdvACrAFeIGaiAVBq1gEgoAKWAsIBvQLEA1j+AjtcT8QIzAOIAc4HtAG2AqsBjgMN5gPWB1rMBPoCvAU4gALHAZQCmwHqAp8BUIEB+gGfAmBDzAHbAaYBI0g8TIUBzAIGas8H1AGpAqABsQbQB9kDa48B2wIBzwSvBXHRAgA=', 'base64')), 4326)::geography),
  ('relation/348891', 'la Bisbal d''Empordà', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAWLqoiXcvv8D2AWECooCygnFBMwMxgn4BJEBngwckAGbApYD4QTeAW28AXcs8wKnAYMBggGVA+QB6QHYAaUBsgOAAo4E6QG8Ay/CAYgC4AYThAJK2gGfBcoC+QHiAUpc6QKICWOkBPQCHD7cAbYB1gGgAoQB0ASmAZAEYJYJVLQGeNwBvA7yAm4k9gRNDfsBWuUBfk30AcsKdW3mAakHbokBPn+YAtECGoEDhAKVAT37BvsFrwmfBu8CjQfbArMEdZkB8QTZAnaXBsABgwOIAbMFggGDAQW/AT+tAc8BvwFVgQP7AvsFfMsCsgELRE2lAW8pxwJhpwEbvwG7AZEB3QJ3L0vEAbUETssE4gXHCJ0B5wLBAu8CowPXAh7FAjlH3wKhAcsBqQEPyQGhAe0DbqsCvASRBHrrA7YGlQKKA58CFdUCd/8BqgLFAaQCBXWDBswf9wY=', 'base64')), 4326)::geography),
  ('relation/345219', 'la Pera', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAUP6rSTYkYEEswz/AbUBdKsBFIcEhwFxIHdqZ8wBf1SlB9MCowOxA6EBTdkBTdkDOj/lAroEwwKhAp0CqwGFBXHlByyFAusBwwGnAT1o0QGjAbMEDr8ElAGhBsAFywa0A/0CvgKIAcgBBLQGsQG+AfcB8AVEgAraA+wIwQZIHpAB/APmAWJ3vgHaBLYBgwHuAfwHsgIw1ANtAw2AAswBE/AB8APNAT6qAooCZtQFZnbEAVZqswF0BilsRHAlvgSVAewB8wLgAmWIA+UCggTHA1pO5gGpBPoBsQaqAX+4BokDbA==', 'base64')), 4326)::geography),
  ('relation/346726', 'la Tallada d''Empordà', ST_SetSRID(ST_GeomFromTWKB(decode('pgABAXuyySWy5IEEgQXsAagB3gGMAaoDuwNoWfwBiQSSAg3iAscCaNsDKB/1AfkCBQtYgwIChwGFAakGMpcCmgH3BM4E4wGSBcsC/AIx/AGpAcQC4wED/wKaAe8BKbsBdYsB7AGPA32PAmyvAQrqAcsF2QO3BAebA8kCJweBAZEEqQQctwHDAdUDT7kFIo8B2AEtCuMBOasB3gXzA+ACywf6A80DZC9oFqIBe94BIV423gGrAkLJASa1A8QBqQWyAgk2I+YCMlAckgLKAtgCduYH3weQDaQB8gGfA90C7QbHAt0B2QK1B4sIxQSxAfEBgwXnAfQE5QUfcZQCc4wG+wPGBc0Clgl72ArxAcwHYdsCxgblAYIMLIYBlAJFE94BugE2wgIVpAJmUJwBQXJ6tgK4BpIC+gLIA6wBrgL3AQOjAVvbAVT3AQKNBMgEzwSGApsDpgONATyrBFbHAYICIFD0A5AClgGMATf4AesBBZABqgIv9gE9aesBD4cFVjXIAvkCCk/gAl0IEOAD0wPAAqIDogPwAziWAUSQAooCMuwB', 'base64')), 4326)::geography);

INSERT INTO public.pois (osm_id, kind, name, geom, area, municipality_id) VALUES
  ('way/171473402', 'supermarket', 'ALDI', ST_SetSRID(ST_GeomFromTWKB(decode('wQCq94ADoKD8Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABI+bwgAPKqPwnjAEYsgEH7AObAWIzbGk4IiQfJiE5IZYF+QQ+HrQClwIhF7YCpwIzVw8PhwXiBA0Miwb2Ba0EuAFdBEkAMQVFF2MfzQE/jwExQRdRFy8NCgyIAWKqArIBogE2', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/3714462380', 'supermarket', 'Adartia', ST_SetSRID(ST_GeomFromTWKB(decode('wQCWr4IDyPn8Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABYdasggOK8/wnDwIEABYBAg5zDl8eF/gDEwAE+QEG8QEJBpsBTh0SYUo6CQGcAwGKAQWyAQEyAIYBABIDmAI8LBwShAFAEp0FmgiQAhQrhwNhBAmWA2YXNhEqLgo0ChAGowGAAzIPuAGTA/YCAkJ3DBkGG4sFHxVHhQHNBJYDQwcvCzHFASIzCJcBHDEMIwYUWEjKAsEBGhwSGBYSGAwcAhwBHAsaERoXFhsSIQwjCCUEJQMjBx8LHREXFQ0TlwJDBgsMI/QBPAADAhsMGxIXGBUcESINJAcmASYCAgASKQchkwGDBSMEuQEc', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/1836751672', 'supermarket', 'Bon Area', ST_SetSRID(ST_GeomFromTWKB(decode('wQD+koID1Oz8Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABafqbggPw6/wnAAN7DAABBVcBAxOLAQA9AgAMAhgCBQsRGWl1AQAJHA0kDRAFCgMKAQoAagAGFI4BBlYACv0BCHEGIQBRCRiVAUDzAh6vAZ8BMSMHAQAXlgHDBEXJARslDCEMnQFQGxKFAWQXFmd2ERhHggELHAUa8AMKGOkDpgIQyAQqK6QBEUAHFAsaH3IrhAEQChgWEhgKHAQcARwLGhEaFxYbEiEMIwgBAB9YP54BCyIJGnPMAh9CZA4mAm4AOp8BUv0BIFMiU0rRAYwBFhoojgECqAECBIABwAEDFDIAAgIEBHoQERIZSIEBChkmiwEEGwGLAQMb', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/11160767159', 'supermarket', 'BonÀrea', ST_SetSRID(ST_GeomFromTWKB(decode('wQCC5vECiqPsJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwACLP7u8QKyouwnmwKlAQMBpAGNAQ0VaXUXFT0tyQG0Af0D4wJQQzUHJQNVAAkKDwlLACUEVwx6TLsHpgZfRwBqBB4kigECBkI3mgTKAskBpAGSAUoiDGQgsAGFAQ4GggO4AagBGSIF9QPtAZIH+QUCAgIC/gLeAQB3AREU8QT/AdcCogIMGgIcARwLHBEYFxYbEiEOIwglAiUBCwPjAqwCAQGZBMcCvAenBv4D5AICAA==', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/340210')),
  ('node/1790773211', 'supermarket', 'Cabrabo', ST_SetSRID(ST_GeomFromTWKB(decode('wQDcuYID2Ij9Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABFoS9ggO2gv0nqwHaAnslxQV5SR4BAgMACQQbQrcBKxcWISZmIPABTAwTXLkBkAecAiyLATKvASiDARcJZR8=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/1868789953', 'supermarket', 'Congelats La Sirena', ST_SetSRID(ST_GeomFromTWKB(decode('wQDSqIIDwOj8Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwACaq6pggPk4fwnvQEAIwK5ARwjCK0BNiEOjQFINgAWAVJEfFjYAZ4BBwANAg0ECwYJBklAJQNFC2MTWxc5ExMTBQMbFQcFCQM9FwcBXx0JAQcAOUARGgcOPAJSGDAUBgQEKgoEI44BVwOvASMVVAEWqgEkDgBUBAtUCwACHPcBAwQaFlLSAQQlvAEACgIKBAoICgoIDAYOBA4CTAhIBBQCAyYXqgEEBB4SZDIYqwFiAlgEtAIeBACaAQgCAAOEAh8AvQEFJAYmArwBACYDmgEVAAEARwKZAwAxAMsBAFsCwwEAqQEA4QIAHQARAC0AFQADoQEXJQFCxQScChUBPwcEHQAJAQkFCQcJCQUJBQ0DCwMlATUFAQBHBQEAJr8BAAEg1wEqqQFiGgYAZhQCAEwOCAJEBBIAEAEEARAECAsGAQwHXE0IBwYJBAkACQAD3AGoAQAQAAgaCh4SGBYSGgoaBBwDHAkcERgXFhsSIQ4BAAAOAVgBUgFIAWaTAQezAhsBAF8H', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/11160767162', 'supermarket', 'Covirán', ST_SetSRID(ST_GeomFromTWKB(decode('wQDq7fECwJzsJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwACKtz18QKcmewnaXUXFYMBYx0RmwFNIQutATUjB7kBGyUDbwDXB9QGjwFXAxwAbjQgLSYigAECBHZj/gPkAgIA3QG8AYwBRiIMeiaoAYsBAgICAsgCwAEkA5wBFacD9wEDAY4IgwcZETotAgOaAV45axEXGL0BHTcuAAKBAVMbGLcDhgMMEAwcBBwDHAscERgXFhsSIQ4jCCUCIwEdB70CmgL9A+MCnAiLBwIBlAWQAw==', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/340210')),
  ('node/1793159692', 'supermarket', 'Damià Olivés', ST_SetSRID(ST_GeomFromTWKB(decode('wQDQroIDwtP8Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABgQGApoIDxtX8J3oAtAED0AEJAfABA/wBKBIgDiwOAD0APQRHA7EBAJsBEBGSAhOEBkQ6DAQAEAoABRwGDgIOAQ4BDAMMBQoHBgkGBwILAAkDCQUJBwcJBwsFDQMtB9UBKQ8DEFdWJ3olxAErmgEZZgsLI6MCKAQBrAFBRQsoKQYJBAkCCQEJAwkFCQcHCwcLAw0DDQANAA0ECwQLBgcIExYJDRU5LVpPXh0OeyoHBIUBPgkGdSYzCAACCRwRGBcWHRIfDiMIJQIlASMHIQ0bERkVAQERAgMpAwkDGwILEZcBAQkFCQcJCQUJBQ0FDQENAA0CDQQLBgkIBwgDCgMKAAwe+gEABp0BGD0G0wIKAQCDAQYNIU0OHwYeaggU', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/1404607210', 'supermarket', 'Dia', ST_SetSRID(ST_GeomFromTWKB(decode('wQDoov0CyIWMKA==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABCtqb/QKwgYwoY25aFMwBOzIlRocBKyGtAT5HNhcW', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/346722')),
  ('node/3683011008', 'supermarket', 'Dia', ST_SetSRID(ST_GeomFromTWKB(decode('wQDAhvMCjpSCKA==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABF8L98gLulIIouAEA1AEAEAAMAw4DCgUKCQYHBAkCCwEJAwkFCQkHCQUNBQsBDQHVAQC7AQAAVAQY', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/348891')),
  ('node/1836748663', 'supermarket', 'Eurospar', ST_SetSRID(ST_GeomFromTWKB(decode('wQCC4YID4NX8Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABHIbdggOg0PwnCFIGWgZaBloGWPECEHkEfwINAAMGCSiMAQEEKtABAwMvkAILCDRSARYFFAsGDQAdARsrACWVBDsUAkY=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/3687040629', 'supermarket', 'Lloveras', ST_SetSRID(ST_GeomFromTWKB(decode('wQCa5YQDzLX5Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABNdbnhAOOr/knFQPFAlg1cQkAJQKFARZCNjZ0DE4FDOUBmgEPci0uSzwxKAMEyQKGAs0BogEAAkqCARIYLjQ0KTgtYlOcAYEBemPMASlSFwADBBsKGxIXGBUeESANJAcmAyYECAIDDSu1ATgHKWsVTRAjBAsACwcz+AOHAZkBLSMH', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/11160767161', 'supermarket', 'Luque', ST_SetSRID(ST_GeomFromTWKB(decode('wQDS7PECtJ3sJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABPujz8QKsmewnAQAAAoEBUxsYxwSGBAQEChwEHAMcCRwRGBcWHRIfDiMIJQIlAQsDtQGiAf0D4wKaB5sGLwUlA10A0QbgBfMBkwEFCgkcFU66AXLDAaQBIHYGDooC4QH+A+QCAgDtArQChAFCIAyGASq2AoMCAgICAsQDhgKcAS8gC54BTxwRhgFjGBVocxIZSIEBDBsYW+0E6gTvA6ECAwHwB+kGCw9ZYw==', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/340210')),
  ('node/11881486468', 'supermarket', 'Maresma', ST_SetSRID(ST_GeomFromTWKB(decode('wQDSx/EC1JHsJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABJczQ8QLwkOwnCSGFA6oCAQLvA6ID2QG2AQEAAAIDAgEEAQIBBAEEAQIABAEEAAIHQFoAJgESAwQdmgF/kgFeShUgDSAPuwF7igPJArwBoAEWGRIXHjWfAYcB/gHBAQBRAxs=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/340210')),
  ('way/362680515', 'supermarket', 'Mercadona', ST_SetSRID(ST_GeomFromTWKB(decode('wQCMhIED9pT8Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABIqqBgQPunvwnBAMhF74CsQImGIYC6QErGfgB7QEmFnprKxdKSSoYJh8mHysbSkEsHMwCtwIfE6AFgQWqAZsBSVEbE6kCsgI3NE9KlwGQAYsD8gJFQssGlgb7A94DlgEsKAY=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/11074054353', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQC464QDgLL5Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwACSIbxhAParPknnQFNIQ09EaMCCxklZSQRAl0ABwD1ARQPAtMBNAMCAQANG5UBTB0SgwFkFxZpdhEYDyIuJjZ0DE4FDNMBjgEALgQcJowBChpKggESGiIoTheiASEVXyu1ATgHKWsVTRAjBAsACwczrASVAdABLdwBMZACogQGCAoKCgYMBg4EDgAOAA4BDAUMBQoHBgkECQIJAAkDCYsClwTkAScKAaACU2tPGxEVlwYsQAt2F04TlAIKLFShAjQDAJsCQAEA0QEwAQCfBJIBXccBjgEtCgM0F9gBP8wBMcQBDR42', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/11880927722', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQCw2PECrpTsJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABQ7TP8QKSlewnAgYSEAQCQDIEAoIBWAEGAAoECgYICAgICK4BaBgQDAYOBA4CCgBSOrMBmAEEBB4SVCraAbcB5AORAx0IJQIlASMHIQ3tAq4Ce1ULBQsFDwENAAUAaT8ABwEJAwsHCQkHeU+iBP8DBgkGCQIJAAkBCQUJBwkJBQsFDQMNAQ0ADQILBAsGCQiXBPgDBQODAW8AhgEEHA==', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/340210')),
  ('node/3044321991', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQDy/vECtqbwJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABH5D88QKAoPAnNRJlvgIAAhtYKYABAQoCCgQMBggICgoGDAYOBA4ADgAOAQwDDAcKBwYHBgkqfwABGldw3QICCQELAQU3CCUI', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/347518')),
  ('node/3222164201', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQC6woYD3MuNKA==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwACCoDDhgPmyY0oAWUGWxZXIGfDAW23As4CrgOOAgQAEGsGpQHRAVw4AzwfPpEBY1pN', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/346722')),
  ('node/3670311505', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQCM+/IC8piCKA==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABGID08gLYlIIoCQyECwrUAQAQAAwDDgMKBQoJBgcECQILAQkDCQUJCQcJBQ0FCwENAdUBAP8JB2FIFxY=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/348891')),
  ('node/5318460690', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQDavYcD+Ib9Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABGPjDhwOKgv0nAQIJBltJhwFDHw2vATUZBdwCmgLTAYAB3QOWAhABJgIkCCIOHhIEBJoD7QHiAYkBLhk8IRIHExFRPQ==', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/345513')),
  ('node/7735007399', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQCQu/sC9K70Jw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABDNTD+wKsrvQnvwbFAWUXkQiFAhUUP0i8CJACZhjABsYBaBoAcTsN', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/344130')),
  ('way/200820575', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQCGhfYC9LPwJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABLZL+9QKasvAnAwoACgQKBgoICgoGDAYMBA4CDgAOAbACRwIAjANl+gN1/gJZjgEhDAMMBQoHCAcECQQJAAkDCwUHBQkLBwkDDQMNAQ0ADQKNASD9Alr5A3YBAIsDZq8CSAsECwYJCAcKAwo=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/347518')),
  ('way/352194673', 'supermarket', 'Spar', ST_SetSRID(ST_GeomFromTWKB(decode('wQCUuIcDmI2BKA==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABB4a4hwPekoEokwGtAoMCjgR+CMABE6gBHU21AQ==', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/343837')),
  ('node/4741531648', 'supermarket', 'Suma', ST_SetSRID(ST_GeomFromTWKB(decode('wQDMvf0CuvGLKA==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwACPJzG/QKw74soSYEBERkdIQK4AekECAOrBAcDIwdjDQLIBCEAAukBtQYDOycPCjLSAVI4hQEADQANBAsECwYHCgcIAwoADAAKBAoICggIDAYMBg4CDgLMAQDeBQICCAzmAoEHBAEAxwMKAgwMGiZEmAMHhAcDFoYENgckBzYPE+UDqAUEIj0MGRpfCa8CAgATSwkZB9sFbuYEBwz8AuMEAw3pAgADAAE=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/346722')),
  ('node/12551368265', 'supermarket', 'Supermercat Jodofi', ST_SetSRID(ST_GeomFromTWKB(decode('wQCgsvYCpKHwJw==', 'base64')), 4326)::geography, ST_SetSRID(ST_GeomFromTWKB(decode('wwABGPK69gKqn/AntQEA1QoVDQANBAsECwgHCAcIAwoBDAIKBAoGCggICgYOBgwCDgLYChYCANQBABdfBQs=', 'base64')), 4326)::geography, (SELECT id FROM public.municipalities WHERE osm_id = 'relation/347518'));

-- Alta: asigna la población a partir del polígono de casa.
CREATE OR REPLACE FUNCTION public.create_character(
  p_nick text, p_age integer, p_sex text, p_eye_color text, p_hair_color text,
  p_height_band text, p_profession text, p_hobby text,
  p_home_lat double precision, p_home_lng double precision)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, extensions, pg_temp AS $$
DECLARE
  v_uid uuid := auth.uid();
  p players%ROWTYPE;
  b age_bands%ROWTYPE;
  v_nick text := btrim(p_nick);
  v_home geography;
  v_muni_id integer;
  v_muni_name text;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'No autenticado' USING ERRCODE = '42501'; END IF;
  SELECT * INTO p FROM players WHERE id = v_uid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Jugador inexistente'; END IF;
  IF EXISTS (SELECT 1 FROM character_profiles WHERE player_id = v_uid) THEN
    RAISE EXCEPTION 'Ya estás en el censo' USING ERRCODE = '23505';
  END IF;
  IF p.current_encounter_id IS NOT NULL THEN RAISE EXCEPTION 'Estás en un encuentro'; END IF;

  IF v_nick !~ '^[A-Za-z0-9ÁÉÍÓÚÜÑáéíóúüñÇç._-]{3,20}$' THEN
    RAISE EXCEPTION 'Nick no válido (3-20 caracteres: letras, números, . _ -)' USING ERRCODE = '22023';
  END IF;
  -- Prefijos reservados por el motor v1 (recuentos por tester%).
  IF lower(v_nick) LIKE 'tester%' OR v_nick LIKE '\_%' THEN
    RAISE EXCEPTION 'Nick reservado' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (SELECT 1 FROM players WHERE lower(nick) = lower(v_nick) AND id <> v_uid) THEN
    RAISE EXCEPTION 'Nick ocupado' USING ERRCODE = '23505';
  END IF;

  SELECT * INTO b FROM age_bands WHERE p_age BETWEEN min_age AND max_age;
  IF NOT FOUND THEN RAISE EXCEPTION 'Edad fuera de rango' USING ERRCODE = '22023'; END IF;

  PERFORM v2_check_option('sex', p_sex);
  PERFORM v2_check_option('eye_color', p_eye_color);
  PERFORM v2_check_option('hair_color', p_hair_color);
  PERFORM v2_check_option('height_band', p_height_band);
  PERFORM v2_check_option('profession', p_profession);
  PERFORM v2_check_option('hobby', p_hobby);

  IF p_home_lat IS NULL OR p_home_lng IS NULL OR p_home_lat NOT BETWEEN -90 AND 90
     OR p_home_lng NOT BETWEEN -180 AND 180 THEN
    RAISE EXCEPTION 'Ubicación de casa no válida' USING ERRCODE = '22023';
  END IF;

  INSERT INTO character_profiles (player_id, fictional_age, sex, eye_color, hair_color, height_band, profession, hobby)
  VALUES (v_uid, p_age, p_sex, p_eye_color, p_hair_color, p_height_band, p_profession, p_hobby);

  UPDATE players SET nick = v_nick, role = 'civil', rank = 'raso', status = 'active', status_until = NULL,
         age_band = b.band, life_max = b.life_max, life = b.life_max,
         food_stock = v2_param('food_start'), infected_at = NULL, outbreak_id = NULL,
         evolution_level = 0, evolution_points = 0, role_points = 0, mutation_points = 0,
         inside_refuge_id = NULL, resting = false, hidden_since = NULL, exit_streak = 0,
         life_pending = 0, overexcited_until = NULL, down_until = NULL, last_effects_at = now()
   WHERE id = v_uid;

  -- El punto solo existe dentro de esta llamada.
  v_home := v2_blob_polygon(ST_SetSRID(ST_MakePoint(p_home_lng, p_home_lat), 4326)::geography,
    v2_param('home_offset_min_m'), v2_param('home_offset_max_m'),
    v2_param('home_radius_min_m'), v2_param('home_radius_max_m'));
  INSERT INTO refuges (type_code, owner_id, area) VALUES ('home', v_uid, v_home);

  -- Población: la del centro del polígono de casa (no se pide al jugador).
  SELECT id, name INTO v_muni_id, v_muni_name FROM municipalities
   WHERE ST_Intersects(area, ST_Centroid(v_home)) ORDER BY id LIMIT 1;
  UPDATE players SET municipality_id = v_muni_id WHERE id = v_uid;

  PERFORM v2_event(v_uid, 'character_created',
    'Censo sanitario-militar completado. Tus datos quedan registrados.', NULL);

  RETURN jsonb_build_object('nick', v_nick, 'age_band', b.band, 'life', b.life_max,
    'life_max', b.life_max, 'food_stock', v2_param('food_start'), 'municipality', v_muni_name);
END $$;

REVOKE ALL ON FUNCTION public.create_character(text, integer, text, text, text, text, text, text, double precision, double precision) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_character(text, integer, text, text, text, text, text, text, double precision, double precision) TO authenticated;
